In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Data preprocessing

In [2]:
df = pd.read_csv('Social_Network_Ads.csv')

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

## Training the Decision Tree model

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt_clf = DecisionTreeClassifier(criterion='entropy', random_state=0)
dt_clf.fit(X_train, y_train)

## Predicting the test set

In [6]:
cust = X_test[:1, :]

y_pred = dt_clf.predict(cust)
y_pred

array([0])

In [7]:
y_pred = dt_clf.predict(X_test)

np.set_printoptions(precision=2)
np.concatenate(
    (
        y_pred.reshape(len(y_pred), 1), 
        y_test.reshape(len(y_test), 1)
    ),
    1
)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0,

## Confusion matrix

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score

c_matrix = confusion_matrix(y_test, y_pred)
c_matrix

array([[61,  7],
       [ 3, 29]])

In [9]:
acc = accuracy_score(y_test, y_pred)
acc

0.9

Our Decision Tree model performed better than logistic regression and linear SVM. However, it did not beat K-NN or Kernel SVM.